experiment:
  name: "default_experiment"
  rounds: 3
  num_clients: 5
  clients_per_round: 5
  seed: 42

drift:
  enabled: true
  types:
    - data
    - model
    - input
  data_drift_clients: [1]
  model_drift_clients: [2]
  input_drift_clients: [3]
  delta_dbi_threshold: 0.2